### ISSUE TITLE
How to know the curvature

### ISSUE THREAD

**Issue by pedefe** [kjerandp/curve-interpolator#13]
Hello,
How to know the curvature (R (radius), and so K=1/R) at each point of the curve ?
Best regards.

**Comment by kjerandp** [comment]
You can currently get the derivative at a given point on the curve using core functionality, but I guess you would need the second derivative for this as well. I'll labeled it as an enhancement, and will try to find some time implementing it, as I'm sure it's useful.

**Comment by pedefe** [comment]
One usage is the autonomous vehicle following a path, as described on [https://www.a1k0n.net/2018/11/13/fast-line-following.html](url) . Main needs are **`nearestPoint`**, `distance`, `normalVector` ,  **`curvature`** or **`radius`** of the curve at this nearest-point on path. Similar properties are provided by Paper.js, but there are too much functionalities regarding your lib.

**Comment by kjerandp** [comment]
Functions for getting curvature (including radius and direction) and position of nearest point, normal vector and more in latest release (v3.1.0)
