### ISSUE TITLE
Heads in the wrong direction

### ISSUE THREAD

**Issue by gap777** [kjerandp/curve-interpolator#5]
Hi,
I'm seeing some behavior with this library that I don't expect. Maybe it's what you expect, and maybe it's a bug.
Here's a snapshot of my app using CurveInterpolator with 0 tension, both inputs (curve vertices) and outputs (points on curve):

<img width="864" alt="Screen Shot 2020-04-27 at 11 19 58 AM" src="https://user-images.githubusercontent.com/6495610/80389554-359b1e00-8879-11ea-8a85-6c0e18f76a2a.png">

Notice that although my first control point is (888.48611,481.364299), and my second is to the left (389.28611,489.364299), the output points head in the wrong direction, to the right: from (888.48611,481.364299) to (915.98924,480.923543).

Any suggestions?

**Comment by kjerandp** [comment]
Thanks. This seems like a bug to me.

I have re-created the issue here and will look into it asap: 

https://observablehq.com/@kjerandp/curveinterpolator-issue-5

**Comment by gap777** [comment]
Thanks! It might be related to the vertex injection you do when there are too few vertices.
Also, if you come up with any work-arounds, I'd appreciate the tip.

**Comment by kjerandp** [comment]
The only thing I can think of right now, is to add more control points, if that's possible in your use case. 

In the observable notebook, I commented out an additional control point as a possible work-around. Remove the comment to see its effect.

**Comment by gap777** [comment]
I see you've started work on a fix! That's great.... and we really appreciate the quick turn-around. There's still one related issue with v2.0.5, which is like an overshoot on the ending of the curve. 
In this attachment:

<img width="716" alt="Screen Shot 2020-04-27 at 5 11 27 PM" src="https://user-images.githubusercontent.com/6495610/80421311-4748e980-88aa-11ea-9d64-ed29ff4a1cfd.png">

We want to terminate at (534.180874,271.18858), curving up towards that point... but in the last few interpolated points, you see one above the point:

.....
(533.588404,294.124162), 
(534.510562,277.522556),  <--- this doesnt belong on the curve
(532.887812,260.980198),   <--- this doesnt belong on the curve
(534.180874,271.18858)

**Comment by kjerandp** [comment]
Fixed in release 2.0.6.

The extrapolation did indeed cause the unexpected behaviour. Thanks for reporting and contributing to solving this issue!

Observable notebook has been updated with the fix added.
